### ISSUE TITLE
Prompt Error: Can't convert types.

### ISSUE THREAD

**Issue by HSIS007** [MythicAgents/apfell#1]
Getting below error while using prompt from Apfell payload.
prompt {"answer":"","icon":"/System/Library/CoreServices/Software Update.app/Contents/Resources/SoftwareUpdate.icns","text":"An application needs permission to update","title":"Application Needs to Update"}
Error: Can't convert types.

![Mythic_Error](https://user-images.githubusercontent.com/15693465/120663487-f7abf880-c481-11eb-9f16-13b76af26438.PNG)

**Comment by its-a-feature** [comment]
Can you provide a bit more context? What version of macOS are you running this on?

**Comment by HSIS007** [comment]
Below is the system info output. BigSur 11.4
system_info 
{
  "applescriptVersion": "2.7",
  "applescriptStudioVersion": "1.5.3",
  "systemVersion": "11.4",
  "shortUserName": "root",
  "longUserName": "System Administrator",
  "userID": null,
  "userLocale": "en",
  "homeDirectory": {},
  "bootVolume": "Macintosh HD:",
  "computerName": "MacBook Pro",
  "hostName": "MacBook-Pro.local",
  "ipv4Address": "192.168.0.66",
  "primaryEthernetAddress": "",
  "cpuType": "Intel x86-64h Haswell",
  "cpuSpeed": 2000,
  "physicalMemory": 8192
}

**Comment by HSIS007** [comment]
I am also getting error with list_users command.

![Mythic_Error_list_users](https://user-images.githubusercontent.com/15693465/120667939-e1a03700-c485-11eb-91f8-0331a490d3aa.PNG)

**Comment by its-a-feature** [comment]
Yup, just tested on an 11.1 machine and those both seem to have issues in Big Sur. Hopefully they'll be easy updates. Thank you for catching that

**Comment by its-a-feature** [comment]
So, following up on this, it appears that for the `prompt` issue is actually JXA's way of indicating that the icon specified doesn't exist. Before Big Sur, that icon was located at:
```
/System/Library/CoreServices/Software Update.app/Contents/Resources/SoftwareUpdate.icns
```
but in Big Sur that icon moved to:
```
"/System/Library/PreferencePanes/SoftwareUpdate.prefPane/Contents/Resources/SoftwareUpdate.icns"
```
It appears that the path was updated in the code, but the default value for the UI popup wasn't changed, so that's a good catch. 

For the `list_users`, it appears as though the CBIdentity isn't available through the Objective C bridge as part of the "Collaboration" services anymore. D00mfist got a workaround for it in the `test_password` command, but we'll have to figure out a solution here.

**Comment by HSIS007** [comment]
Ok great, thank you for the response. I will test it tomorrow first thing.

**Comment by HSIS007** [comment]
Changing the icns file path worked for me, thank you so much.

![image](https://user-images.githubusercontent.com/15693465/120774193-f5957880-c519-11eb-9c3b-ac23176c9d80.png)

**Comment by D00MFist** [comment]
Sorry I'm seeing this late but added a [pull request](https://github.com/MythicAgents/apfell/pull/2) to address the `list_users` command. My bad when testing I was using specific groups and missed the "all" enumeration. Had to change the functionality a little bit so it now always enumerates by groups using the `Collaboration` API. 

Also if you want to enumerate local users using the `Open Directory` API then the`Get_LocalUser` function in [Orchard ](https://github.com/its-a-feature/Orchard/tree/master) can  accomplish this.
